version: '3'
services:
  bot:
    restart: unless-stopped
    container_name: hazzikostas_bot_PROD
    image: discord_hazzikostas
    networks:
      - bots
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    environment:
      - TZ=Europe/Madrid
networks:
  bots:
    external: true
