version: '3'
services:
  bot:
    restart: unless-stopped
    container_name: hazzikostas_bot_PROD
    image: discord_hazzikostas
    networks:
      - bots
      - backend
networks:
  bots:
    external: true
  backend:
    external: true



